apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: my-test-run-
spec:
  pipelineRef:
    name: test-pipeline
  params:
    - name: url
      value: 'https://github.com/yuhkih/go-http.git'
    - name: IMAGE
      value: 'yuhkih/go-http:latest'  # buildah Cluster Task での Push 先 (=生成されるイメージのタグ名)
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:  # pipelinerun 毎に作られる。pipelrinerun を消すと消える
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100M
