apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  workspaces:
    - name: shared-workspace
  # タスクに渡されるパラメーター。値は、 CLI だったりさらに上位の PipelineRun から渡される
  params:
    - name: url
      type: string
    - name: IMAGE
      type: string
  tasks:
    #  Repository から Source を取得して workspace に保存
    - name: git-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace
    # workspace に保存されたコードを Build して  push 
    - name: buildah
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
        - git-clone 
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: SKIP_PUSH  # PUSH はレジストリが必要なので、実験環境を簡単にするためにここではスキップ
          value: "true"  # ここを false にする場合はレジストリ周りのセットアップが必要
      workspaces:
        - name: source
          workspace: shared-workspace
